import { InsertProject, ProjectCategory, ProjectStatus } from '@shared/schema';

// Mock project data
export const mockProjects: InsertProject[] = [
  {
    name: "Медицинская помощь в Кении",
    nameEn: "Medical Aid in Kenya",
    shortDescription: "Проект по оказанию базовой медицинской помощи в отдаленных деревнях Кении",
    shortDescriptionEn: "Project providing basic medical aid in remote Kenyan villages",
    fullDescription: "Волонтеры проекта работают в передвижных медицинских пунктах, оказывающих базовую помощь жителям отдаленных деревень Кении. В обязанности волонтеров входит помощь медицинскому персоналу, ведение учета пациентов, организация санитарно-просветительской работы среди местного населения.",
    fullDescriptionEn: "Volunteers in this project work in mobile medical units providing basic healthcare to residents of remote Kenyan villages. Volunteer responsibilities include assisting medical staff, keeping patient records, and organizing health education activities among the local population.",
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-08-15"),
    recruitmentDeadline: new Date("2025-05-15"),
    category: ProjectCategory.MEDICAL,
    status: ProjectStatus.ACTIVE,
    location: "Найроби, Кения",
    locationEn: "Nairobi, Kenya",
    country: "Кения",
    countryEn: "Kenya",
    latitude: "1.2921",
    longitude: "36.8219",
    organizationName: "Врачи без границ",
    organizationNameEn: "Doctors Without Borders",
    conditions: "Проживание в волонтерском доме. Питание включено. Транспорт до места работы предоставляется организацией.",
    conditionsEn: "Accommodation in a volunteer house. Meals included. Transportation to work location provided by the organization.",
    volunteerFunction: "Ассистирование врачам, ведение документации, проведение информационных сессий для местных жителей по вопросам базовой гигиены и профилактики заболеваний.",
    volunteerFunctionEn: "Assisting doctors, maintaining documentation, conducting information sessions for locals on basic hygiene and disease prevention.",
    curatorName: "Мария Иванова",
    curatorEmail: "m.ivanova@globvolunteer.org",
    curatorPhone: "+7 (999) 123-45-67",
    images: [
      "https://images.unsplash.com/photo-1584515933487-779824d29309?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1607000975648-161c83bb7cf1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
    ],
    videos: []
  },
  {
    name: "Образовательный проект в Непале",
    nameEn: "Educational Project in Nepal",
    shortDescription: "Преподавание английского языка детям в сельских школах Непала",
    shortDescriptionEn: "Teaching English to children in rural schools of Nepal",
    fullDescription: "Проект направлен на улучшение уровня английского языка среди детей в сельских районах Непала. Волонтеры работают в местных школах, проводя уроки английского языка и организуя дополнительные образовательные мероприятия. Проект также включает в себя культурный обмен и помощь в развитии школьной инфраструктуры.",
    fullDescriptionEn: "This project aims to improve English language skills among children in rural areas of Nepal. Volunteers work in local schools, conducting English lessons and organizing additional educational activities. The project also includes cultural exchange and assistance in developing school infrastructure.",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-09-30"),
    recruitmentDeadline: new Date("2025-06-01"),
    category: ProjectCategory.EDUCATION,
    status: ProjectStatus.ACTIVE,
    location: "Катманду, Непал",
    locationEn: "Kathmandu, Nepal",
    country: "Непал",
    countryEn: "Nepal",
    latitude: "27.7172",
    longitude: "85.3240",
    organizationName: "Образование для всех",
    organizationNameEn: "Education for All",
    conditions: "Проживание в принимающих семьях. Питание включено. Волонтеры добираются до школы пешком (15-20 минут ходьбы).",
    conditionsEn: "Accommodation with host families. Meals included. Volunteers walk to school (15-20 minutes).",
    volunteerFunction: "Преподавание английского языка, организация внеклассных мероприятий, помощь в подготовке учебных материалов, культурный обмен с местными учителями и учениками.",
    volunteerFunctionEn: "Teaching English, organizing extracurricular activities, assisting in the preparation of educational materials, cultural exchange with local teachers and students.",
    curatorName: "Алексей Петров",
    curatorEmail: "a.petrov@globvolunteer.org",
    curatorPhone: "+7 (999) 234-56-78",
    images: [
      "https://images.unsplash.com/photo-1597633244018-0797674bee51?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1564385503889-52053000e2a4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
    ],
    videos: []
  },
  {
    name: "Спортивный лагерь в Бразилии",
    nameEn: "Sports Camp in Brazil",
    shortDescription: "Организация спортивных мероприятий для детей из малоимущих семей в Рио-де-Жанейро",
    shortDescriptionEn: "Organizing sports activities for children from low-income families in Rio de Janeiro",
    fullDescription: "Проект направлен на социальную адаптацию детей из малоимущих семей через спорт. Волонтеры организуют регулярные спортивные тренировки по футболу, волейболу и другим видам спорта, а также проводят образовательные мероприятия о здоровом образе жизни. Проект помогает детям развивать не только физические навыки, но и командный дух, лидерские качества и дисциплину.",
    fullDescriptionEn: "This project focuses on social adaptation of children from low-income families through sports. Volunteers organize regular sports training in football, volleyball, and other sports, as well as educational activities about healthy lifestyles. The project helps children develop not only physical skills but also team spirit, leadership qualities, and discipline.",
    startDate: new Date("2025-01-15"),
    endDate: new Date("2025-03-15"),
    recruitmentDeadline: new Date("2024-12-15"),
    category: ProjectCategory.SPORTS,
    status: ProjectStatus.ACTIVE,
    location: "Рио-де-Жанейро, Бразилия",
    locationEn: "Rio de Janeiro, Brazil",
    country: "Бразилия",
    countryEn: "Brazil",
    latitude: "-22.9068",
    longitude: "-43.1729",
    organizationName: "Спорт для всех",
    organizationNameEn: "Sports for All",
    conditions: "Проживание в волонтерском центре. Питание частично включено (завтрак и обед). Транспорт до места проведения мероприятий предоставляется организацией.",
    conditionsEn: "Accommodation in a volunteer center. Meals partially included (breakfast and lunch). Transportation to the event location provided by the organization.",
    volunteerFunction: "Проведение спортивных тренировок, организация турниров и соревнований, проведение образовательных мероприятий о здоровом образе жизни.",
    volunteerFunctionEn: "Conducting sports training, organizing tournaments and competitions, conducting educational activities about healthy lifestyles.",
    curatorName: "Ольга Смирнова",
    curatorEmail: "o.smirnova@globvolunteer.org",
    curatorPhone: "+7 (999) 345-67-89",
    images: [
      "https://images.unsplash.com/photo-1459865264687-595d652de67e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1514287981605-98a47aaab9a7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
    ],
    videos: []
  },
  {
    name: "Экологический проект в Коста-Рике",
    nameEn: "Environmental Project in Costa Rica",
    shortDescription: "Защита морских черепах и очистка пляжей в Коста-Рике",
    shortDescriptionEn: "Protection of sea turtles and beach cleanup in Costa Rica",
    fullDescription: "Проект направлен на защиту морских черепах, находящихся под угрозой исчезновения, и сохранение прибрежных экосистем. Волонтеры патрулируют пляжи в ночное время для защиты черепашьих гнезд от браконьеров, помогают в сборе данных о численности и миграции черепах, а также участвуют в мероприятиях по очистке пляжей от пластикового мусора и просвещению местного населения о важности защиты окружающей среды.",
    fullDescriptionEn: "This project aims to protect endangered sea turtles and preserve coastal ecosystems. Volunteers patrol beaches at night to protect turtle nests from poachers, help collect data on turtle numbers and migration, and participate in activities to clean beaches of plastic waste and educate local populations about the importance of environmental protection.",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2025-01-31"),
    recruitmentDeadline: new Date("2024-10-01"),
    category: ProjectCategory.ENVIRONMENT,
    status: ProjectStatus.ACTIVE,
    location: "Торрехульо, Коста-Рика",
    locationEn: "Tortuguero, Costa Rica",
    country: "Коста-Рика",
    countryEn: "Costa Rica",
    latitude: "10.5429",
    longitude: "-83.5050",
    organizationName: "Зеленый мир",
    organizationNameEn: "Green World",
    conditions: "Проживание в экологическом лагере (базовые условия). Питание включено. Волонтеры делят между собой обязанности по приготовлению пищи и уборке.",
    conditionsEn: "Accommodation in an eco-camp (basic conditions). Meals included. Volunteers share cooking and cleaning duties.",
    volunteerFunction: "Патрулирование пляжей, мониторинг черепашьих гнезд, сбор данных, участие в образовательных программах для местного населения, очистка пляжей от мусора.",
    volunteerFunctionEn: "Beach patrol, monitoring turtle nests, data collection, participation in educational programs for the local population, beach cleanup.",
    curatorName: "Иван Соколов",
    curatorEmail: "i.sokolov@globvolunteer.org",
    curatorPhone: "+7 (999) 456-78-90",
    images: [
      "https://images.unsplash.com/photo-1520551775756-d481df50f47f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1582910184841-2135ce2eaecd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
    ],
    videos: []
  },
  {
    name: "Медицинский проект в Индии",
    nameEn: "Medical Project in India",
    shortDescription: "Помощь в сельской клинике и организация медицинских лагерей в Индии",
    shortDescriptionEn: "Assistance in a rural clinic and organization of medical camps in India",
    fullDescription: "Проект предлагает возможность работы в сельской клинике штата Тамил Наду, оказывающей медицинскую помощь жителям отдаленных деревень. Волонтеры помогают врачам и медсестрам в ежедневной работе клиники, а также участвуют в организации выездных медицинских лагерей, где проводятся базовые обследования, вакцинация и санитарно-просветительская работа.",
    fullDescriptionEn: "The project offers an opportunity to work in a rural clinic in Tamil Nadu state, providing medical assistance to residents of remote villages. Volunteers help doctors and nurses in the daily work of the clinic, as well as participate in organizing mobile medical camps where basic examinations, vaccinations, and health education are conducted.",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-04-30"),
    recruitmentDeadline: new Date("2025-01-15"),
    category: ProjectCategory.MEDICAL,
    status: ProjectStatus.ACTIVE,
    location: "Ченнаи, Индия",
    locationEn: "Chennai, India",
    country: "Индия",
    countryEn: "India",
    latitude: "13.0827",
    longitude: "80.2707",
    organizationName: "Здоровье для всех",
    organizationNameEn: "Health for All",
    conditions: "Проживание в гостевом доме при клинике. Питание включено. Базовые удобства (горячая вода, электричество могут быть с перебоями).",
    conditionsEn: "Accommodation in a guest house at the clinic. Meals included. Basic amenities (hot water, electricity may be intermittent).",
    volunteerFunction: "Помощь медицинскому персоналу, административная работа, организация медицинских лагерей, санитарно-просветительская работа в местных школах.",
    volunteerFunctionEn: "Assisting medical staff, administrative work, organizing medical camps, health education in local schools.",
    curatorName: "Екатерина Морозова",
    curatorEmail: "e.morozova@globvolunteer.org",
    curatorPhone: "+7 (999) 567-89-01",
    images: [
      "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1504439468489-c8920d796a29?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
    ],
    videos: []
  },
  {
    name: "Образовательный проект в Танзании",
    nameEn: "Educational Project in Tanzania",
    shortDescription: "Преподавание в начальной школе в сельском районе Танзании",
    shortDescriptionEn: "Teaching in a primary school in a rural area of Tanzania",
    fullDescription: "Проект предлагает возможность работы в начальной школе деревни Мванза, где волонтеры помогают местным учителям в проведении уроков английского языка, математики и естественных наук. Помимо преподавания, волонтеры участвуют в организации внешкольных мероприятий, включая спортивные и творческие занятия, а также помогают в улучшении школьной инфраструктуры.",
    fullDescriptionEn: "The project offers an opportunity to work in a primary school in the village of Mwanza, where volunteers help local teachers conduct lessons in English, mathematics, and natural sciences. In addition to teaching, volunteers participate in organizing extracurricular activities, including sports and creative activities, and help improve school infrastructure.",
    startDate: new Date("2025-03-15"),
    endDate: new Date("2025-06-15"),
    recruitmentDeadline: new Date("2025-02-15"),
    category: ProjectCategory.EDUCATION,
    status: ProjectStatus.ACTIVE,
    location: "Мванза, Танзания",
    locationEn: "Mwanza, Tanzania",
    country: "Танзания",
    countryEn: "Tanzania",
    latitude: "-2.5164",
    longitude: "32.9035",
    organizationName: "Образование - будущее",
    organizationNameEn: "Education is Future",
    conditions: "Проживание в доме учителей при школе. Питание частично включено (завтрак и обед в школьной столовой). Ужин волонтеры готовят самостоятельно.",
    conditionsEn: "Accommodation in the teachers' house at the school. Meals partially included (breakfast and lunch in the school cafeteria). Volunteers prepare dinner themselves.",
    volunteerFunction: "Преподавание английского языка, математики, естественных наук. Организация внеклассных мероприятий. Помощь в улучшении школьной инфраструктуры.",
    volunteerFunctionEn: "Teaching English, mathematics, and natural sciences. Organizing extracurricular activities. Helping to improve school infrastructure.",
    curatorName: "Дмитрий Васильев",
    curatorEmail: "d.vasiliev@globvolunteer.org",
    curatorPhone: "+7 (999) 678-90-12",
    images: [
      "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1550475618-b0db154438d6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
    ],
    videos: []
  }
];